"""add auth user id

Revision ID: 00f1cac8ffde
Revises: a9980cde0186
Create Date: 2026-08-26 23:54:52.890410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f1cac8ffde'
down_revision: Union[str, Sequence[str], None] = 'a9980cde0186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_user_id', default=None, server_default=None, type_=sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['auth_user_id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'auth_user_id')
    # ### end Alembic commands ###
